name: "CloudCamp CI"
on:
  push:
  workflow_dispatch: 
    inputs:
      should_deploy: 
        description: "Should deploy?"
        type: boolean

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, World!"
      - name: "checkout"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #Version 4.2.2
      
      - name: "print files"
        run: |
          ls
          pwd

  job-dependency:
    if: ${{ inputs.should_deploy }}
    runs-on: ubuntu-latest
    needs: [hello-world]
    steps:
      - run: echo "${{ github.actor }}"

  terraform:
    name: "Terraform CI"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
      - name: "checkout"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #Version 4.2.2
      
      - name: "install terraform"
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd #Version 3.1.2

      - name: "terraform version"
        run: terraform version

      - name: "terraform init"
        run: terraform init

      - name: "terraform plan"
        run: terraform plan